# Generated by Django 5.2.14 on 2026-08-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('renda_fixa', 'Renda Fixa'), ('acoes', 'Ações'), ('fiis', 'FIIs'), ('cripto', 'Criptomoedas'), ('outros', 'Outros')], default='renda_fixa', max_length=20)),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rentabilidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('data_aplicacao', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
