# Generated by Django 5.2.14 on 2026-08-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='cor',
            field=models.CharField(default='#2563EB', max_length=7),
        ),
    ]
