# Generated by Django 5.2.14 on 2026-05-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cartao_familia_despesacompartilhada_membrofamilia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterModelOptions(
            name='despesacompartilhada',
            options={'verbose_name': 'Despesa Compartilhada', 'verbose_name_plural': 'Despesas Compartilhadas'},
        ),
        migrations.AlterModelOptions(
            name='membrofamilia',
            options={'verbose_name': 'Membro da Família', 'verbose_name_plural': 'Membros da Família'},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
