# Generated by Django 5.2.6 on 2026-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cartao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil do usuário no sistema', null=True, upload_to='perfil_fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
